### PR TITLE
⬆️ empress-blog-ember-template

### PR DESCRIPTION
**Pull request by amyrlam**
## What it does

This update will move "2021" to a year tag on the blog

### CODE REVIEW

**Comment by amyrlam** [comment]
WAS: 
image

IS: 
2021 will be under "By year"

**Review by mansona — APPROVED** [review]
Looks great!

**Comment by mansona** [comment]
Hey @amyrlam just to let you know that you probably need to upgrade your npm, you were downgrading the package-lock.json because you don't have npm@7. It's easy enough to upgrade: `npm i -g npm` 

I fixed this PR and also added a check to CI to make sure we don't have this issue in future 👍

**Comment by amyrlam** [comment]
@mansona whoops, sorry about that. thanks, updated!

**Pull request merged**
