### PR TITLE
blog(embertimes#184): add section on ember-engines@0.8.18

### PR DESCRIPTION
**Pull request by jayjayjpg**
This adds a section about the recent release announcement of [ember-engines](https://twitter.com/MVillander/status/1406367740668092420).

I noticed a build error locally which I was able to resolve by replacing `hbs` to `html` in the syntax annotation for one of the code examples in the file. Let me know if I should revert the change if this is not a general build issue and just occurred for me locally and thank you for taking a look!

## Ember Times review template

- [x] Add your name to top and bottom
- [x] Put emoji in writeup title
- [x] Add a short blurb (could be the title) to the beginning
- [x] Link to external article/repo/etc in paragraph/body text, not just the writeup title (link in writeup title is optional now)
- [x] Add the contributor in the post in format "FirstName LastName (@githubUserName)" linked to their GitHub account
- [x] Check that all links work

## Related Issue(s)

Related to https://github.com/ember-learn/ember-blog/pull/991

### CODE REVIEW

**Review by MinThaMie — CHANGES_REQUESTED** [review]
Awesome write-up :D

**Review by MinThaMie — APPROVED** [review]
Awesome write-up, sorry for the wrong click for the request changes  :)

**Comment by jayjayjpg** [comment]
@MinThaMie Thank you for the swift review! 🙇🏾‍♀️

**Comment by amyrlam** [comment]
thank you both so much! 💯

@jayjayjpg tbh, am not sure about the build error or what does the code samples. will take a closer look, added it to the PR list if don't get to it before publish

**Pull request merged**
