### PR TITLE
Add Feeder to Ember Times

### PR DESCRIPTION
**Pull request by amyrlam**

### CODE REVIEW

**Comment by amyrlam** [comment]
@erkie Do you want to add any more detail about the Corona dashboard / Ember usage at Feeder? Feel free to commit / comment directly to the branch! Or #support-ember-times on Discord

We've done some past "Ember at Company x" writeups and seems like readers like them!

**Comment by erkie** [comment]
@amyrlam so cool! I’ll see if I can add some more detail or come up with some more info tomorrow if that’s OK?

**Comment by amyrlam** [comment]
@erkie sure sounds good, thanks for being up for it! Anytime before Friday is cool, or can always be pushed to a future issue if you prefer

**Review by hergaiety — APPROVED** [review]

**Review by hergaiety — COMMENTED** [review]
Haha I approved early without thinking, it's just a draft doh! Still learning to open source a bit :sweat_smile:

**Comment by erkie** [comment]
I'm not sure how much detail to go into, what's relevant in this context and more, so I just kinda went nuts with things related to our Ember usage. Feel free to do whatever you want with it. Ignore it, take some tidbits, add it all! 

> Do you want to add any more detail about the Corona dashboard / Ember usage at Feeder? 

We started at Ember 2.10 and are now at Ember 3.14 and counting. It's so cool for that the upgrades help to educate us how to become better developers. One striking thing is the a11y template linting rules that promote best practices. I had no idea about those things, but now I do! So thanks Ember.

We've used pods since the start, but I got tripped up by all the tabs in Atom being called "component.js", or "template.hbs", which is why I developed the Atom addon Ember tabs: https://atom.io/packages/ember-tabs Was really happy when scrolling through ember-cli docs one day and found it mentioned here: https://ember-cli.com/user-guide/#atom So far I haven't kept up to date with the module unification, but it seems promising!

TypeScript is the single biggest innovation in many years. The type safety cannot be quickly adds  and the ember-cli-typescript addon has been an amazing bridge. It's great to see that a lot of Ember internal packages are now written entirely with Typescript (https://github.com/emberjs/ember.js/tree/master/packages/@ember/-internals/glimmer)

We render a lot of components on screen, so [performance has been something we've invested a lot of time into](https://discuss.emberjs.com/t/baseline-performance-of-rendering-components-is-slow/9707/11) Switching to Glimmer components for high volume components we were able to reduce render times on hotspots with ~20%.

**Comment by amyrlam** [comment]
@sharpshark28 no worries, review any draft anytime! thanks for your help!

@erkie I think that this is awesome, huge thank you! 🎉 I will finish any copy editing tomorrow and get it into the issue.I think I'll take come copy from your homepage, something like `Feeder is the news manager that tracks any online source you choose and bundles it into an easy-to-digest reading experience.`

**Comment by amyrlam** [comment]
brought this over to https://github.com/ember-learn/ember-blog/pull/578 manually with some minor edits

**Pull request closed without merging**
