### PR TITLE
Add Ember Camp writeup

### PR DESCRIPTION
**Pull request by amyrlam**
@EndangeredMassa Really appreciate you sharing this and doing the writeup! Let me know what you think, can make further changes as needed!
 
Real question: Is 🌭 an acceptable Chicago emoji?

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
> Let me know what you think, can make further changes as needed!

Looks good!

> Real question: Is 🌭 an acceptable Chicago emoji?

I'll speak for all of Chicago: Yup!

**Review by MinThaMie — APPROVED** [review]
Awesome :)

**Comment by amyrlam** [comment]
Yay about 🌭...I have actually never been to Chicago so hope to make it this year 🤞

**Comment by amyrlam** [comment]
thanks @MinThaMie and @EndangeredMassa

**Pull request merged**
