### PR TITLE
Update and rename anne-greeth

### PR DESCRIPTION
**Pull request by amyrlam**
## What it does

Update Anne Greeth's name

## Related Issue(s)

Follow-on to: https://github.com/ember-learn/ember-blog/pull/1021

### CODE REVIEW

**Comment by MinThaMie** [comment]
I've been discussing this with @mansona too. I've already committed this in the branch for the times of this week. I think we need to do a full find and replace of all my "articles" so that it updates everywhere. Otherwise all my old articles are broken.

**Comment by amyrlam** [comment]
@MinThaMie you are so right, apologies i missed that! 🤦‍♀️ let's leave this on hold until after friday then?

**Comment by MinThaMie** [comment]
Screenshot 2021-08-25 at 11 17 45
Tadaa, this looks amazing :)

**Review by MinThaMie — APPROVED** [review]
super happy with this :) thanks @amyrlam and @mansona

**Pull request merged**
