### PR TITLE
EmberTimes no. 211

### PR DESCRIPTION
**Pull request by MinThaMie**
**Content**
- [x] Ember Europe 18th of July
- [x] EmberConf videos -> https://youtube.com/playlist?list=PL4eq2DPpyBbljzNStMjnoDA0NZM61yCEq&si=cWNIFAnxg_Z9pbYW
- [x] https://www.linkedin.com/games
- [x] Ember guides template tag https://guides.emberjs.com/release/components/template-tag-format/
- [x] Named blocks guides Shirin -> https://guides.emberjs.com/release/components/block-content/#toc_named-blocks

**EmberData aka WarpDrive**
- [x] Live coding WarpDrive -> https://www.youtube.com/watch?v=YagBVhaq_NM
- [x] EmberData 5.3.4 -> https://github.com/emberjs/data/releases/tag/v5.3.4

**New addons**
- [x] flash notifications -> https://ember-flash-notifications.vercel.app/
- [x] new add-on -> https://github.com/NullVoxPopuli/form-data-utils
- [x] https://github.com/ijlee2/ember-codemod-remove-inject-as-service
- [x] https://github.com/alexeipanov/ember-awesome-icons
- [x] https://github.com/IgnaceMaes/ember-phosphor-icons
- [x] ember-engines-router-service -> https://www.npmjs.com/package/ember-engines-router-service

**Updates**
- [x] https://github.com/alexlafroscia/ember-cli-polyfill-io/pull/10 -> security fix polyfill.io
- [x] addon-v2-scanner https://github.com/IgnaceMaes/ember-addon-v2-scanner
- [x] v4.1.0 https://github.com/ember-a11y/ember-a11y-refocus
- [x] Qunit theme https://github.com/emberjs/ember-qunit/releases/tag/v8.1.0
- [x] ember-into v7 -> https://github.com/ember-intl/ember-intl/releases/tag/v7.0.0
- [x] embertooling.vscode-ember -> template-lint https://discord.com/channels/480462759797063690/480499624663056390/1240355130696536184
- [x] eslint-config v4 -> https://discord.com/channels/480462759797063690/480499624663056390/1240068093326393384
- [ ] Formats supports `gts` `gjs` hbs` -> https://github.com/formatjs/formatjs/commit/1693515a03278a3cfff5a16a9c7ca708c8a0e54e
- [ ] fastboot 4.1.3 https://github.com/ember-fastboot/ember-cli-fastboot/releases/tag/v4.1.3-ember-cli-fastboot

### CODE REVIEW

**Comment by mkszepp** [comment]
If you like you can add:

- Ember can was moved to v2 addon and TS https://github.com/minutebase/ember-can/releases/tag/v5.0.0
- ember sortable , added grid support https://github.com/adopted-ember-addons/ember-sortable/releases/tag/v5.1.0-ember-sortable
- ember string v4 (moved to v2 addon) https://github.com/emberjs/ember-string/releases/tag/v4.0.0-%40ember%2Fstring

**Comment by MinThaMie** [comment]
> If you like you can add:
> 
> * Ember can was moved to v2 addon and TS https://github.com/minutebase/ember-can/releases/tag/v5.0.0
> * ember sortable , added grid support https://github.com/adopted-ember-addons/ember-sortable/releases/tag/v5.1.0-ember-sortable
> * ember string v4 (moved to v2 addon) https://github.com/emberjs/ember-string/releases/tag/v4.0.0-%40ember%2Fstring

Thanks for mentioning this, I'

**Comment by SergeAstapov** [comment]
[ember-modifier@4.2](https://github.com/ember-modifier/ember-modifier/releases/tag/v4.2.0) has some updates:
* Ember Inspector Support for modifiers is on the way and now there is a way to name modifiers created with arrow syntax
* Added TS support for the blueprints

**Comment by MinThaMie** [comment]
> [ember-modifier@4.2](https://github.com/ember-modifier/ember-modifier/releases/tag/v4.2.0) has some updates:
> 
> * Ember Inspector Support for modifiers is on the way and now there is a way to name modifiers created with arrow syntax
> * Added TS support for the blueprints

Thanks @SergeAstapov, I'll move this to the next times. Feel free to write the write-up yourself :)

**Pull request merged**
