### PR TITLE
Update uELS options

### PR DESCRIPTION
**Pull request by amyrlam**
## What it does

Include more editors in uELS writeup. Follow-on to https://github.com/ember-learn/ember-blog/pull/1004#issuecomment-889802615

### CODE REVIEW

**Comment by amyrlam** [comment]
@lifeart thanks again for your help! I can't assign you as a reviewer so tagging inline

**Review by jayjayjpg — APPROVED** [review]
This reads great, thank you for the update! :sparkles:

**Review by lifeart — APPROVED** [review]

**Comment by lifeart** [comment]
@amyrlam looks very good, thank you!

**Comment by amyrlam** [comment]
@lifeart @jayjayjpg thanks, much appreciated (again)!

**Pull request merged**
