### PR TITLE
ci(markdown): re-enable markdown linting (see #284)

### PR DESCRIPTION
**Pull request by jayjayjpg**
## What it does

This reenables the markdown linting step in CI after merging #284

### CODE REVIEW

**Comment by amyrlam** [comment]
lgtm. Are any of these rules no value added? https://github.com/ember-learn/ember-blog/blob/master/.markdownlint.json

Some of them I added such as `no-trailing-punctuation`, `no-trailing-spaces`, because it makes the diffs easier to review.

**Comment by jayjayjpg** [comment]
@amyrlam I think the rules that we have so far are useful! I think that switching on the rules requires them to to be set to `true` in the config file, unless they're already set to `true` in the default config of the linter, but I haven't checked yet, how the default config actually looks like

I can take another look into it though or as you suggested, we can also brainstorm with the Times team, to see which rules make most sense for us

**Comment by amyrlam** [comment]
Oh yeah, sorry those are false haha 🙈

**Review by amyrlam — APPROVED** [review]
down to merge it in, and if the rules are proving cumbersome, can iterate?

**Comment by jayjayjpg** [comment]
> down to merge it in, and if the rules are proving cumbersome, can iterate?

@amyrlam Yes, sounds good :sparkles:

**Pull request merged**
