### PR TITLE
The Ember Times No. 141 - March 27th 2020

### PR DESCRIPTION
**Pull request by amyrlam**
📝 Ideas, feel free to add to list or claim!

- [ ] RFC: `{{set}}` helper https://github.com/emberjs/rfcs/pull/594
- [ ] Release of `ember-arg-types`
  - https://twitter.com/jonkilroy/status/1242639546749255681
- [x] Porting a Site to Ember with Percy
  - https://simplabs.com/blog/2020/03/27/porting-a-site-to-ember-with-percy/ (🔏 @jessica-jordan)
- [x] Barcode scanner for Ember apps: https://github.com/evocount/ember-scanner
Thank you very much to the ember-times Team for bringing us exciting news week after week! Just let me throw in that QR (and barcode) scanning without a growth in bundle size (thanks ember-auto-import) has been available for much longer through https://github.com/evocount/ember-scanner ... ping @ ttill on discord for short writeup? I think it's @ttill on GitHub? (:lock: @amyrlam)
- [x] We at Feeder also built a COVID-19 aka Corona Dashboard, but for incoming news on the subjects such as news, travel advice and research. It’s also built with Ember.js! It can be found here: https://feeder.co/reader/corona It’s built using our regular stack that ingests public RSS feeds and filters on a set of keywords. https://discuss.emberjs.com/t/ember-js-the-ember-times-issue-no-139/17631/2?u=amyrlam ... ping on discuss for short writeup? (:lock: @amyrlam) 
- [x] Diving into the difference between Ember component invocation when using curlies, angle brackets, and s-expression in Ember templates. (🔒 @ijlee2 )
  - https://twitter.com/0xADADA/status/1241734169937481730 (reply to tweet if questions!)
- [x] Release of Tracked Built-Ins v1.0.0 (🔒 @ijlee2 )
  - https://twitter.com/pzuraq/status/1240069037364633600
- [x] Ember Template Lint Rule from Addon (🔒 @chrisrng )
  - https://mehulkar.com/blog/2020/03/ember-template-lint-rule-from-addon/
- [x] Refactoring Ember Templates - Quick Tip! (🔒 @MinThaMie )
  - https://abhilashlr.in/ember-refactor-templates
- [x] Release of ember-autostash-modifier (:lock: @jaredgalanis) 
  - https://twitter.com/nullvoxpopuli/status/1239325059656933376
- [x] Ember Octane: Let's Go
  - https://yehudakatz.com/2020/03/25/ember-octane-lets-go/ (:lock: @jaredgalanis) 
- [x] EmberConf videos online (maybe mention `#EmberConFriends` again?)
  - https://www.youtube.com/playlist?list=PL4eq2DPpyBbkC03mdzlyej6tcbEqrZK8N (:lock: @jaredgalanis)
- [x] Release of [eslint-plugin-decorator-position](https://github.com/NullVoxPopuli/eslint-plugin-decorator-position) (:lock:  @NullVoxPopuli) 

📆 Future stories
- [ ] **UPDATE** _this should go out in the 2/28 issue per 2/20 learning team meeting_ Write up on current website update status. Call for contributors, explaining the styleguide and which projects contributors can help with. Ping @mansona when this topic is due for release in the Times (Amy note 3/13: is this still valid?)
- [ ] More octane at company x stories? Square, others? (Amy note 3/13: pinged Dean @ Square on Twitter)
- [ ] Outstanding Team Quotes about Octane from https://github.com/ember-learn/ember-blog/pull/459 (Amy note 3/13: is this still valid?)
  * @MelSumner  
  * @kategengler
  * @mixonic
  * @pzuraq

🤔 Questions?

See #support-ember-times on Discord or CONTRIBUTING.

✅ Todos:

- [ ] check all header links are also in the body, and add to template

- Check https://github.com/ember-learn/whats-new-in-emberland (roundup of all the PRs in emberjs and ember-learn repos) for ideas
- Use https://github.com/ember-learn/emberjs-times-tools README
- Check Netlify preview, to ensure display on emberjs.com/blog is good
  - [ ] Check buttons
- [ ] Crosspost on dev.to, delete Readers Question picture, add Canonical URL 
- [ ] Set up tweet for Monday morning on tweetdeck
  - [ ] post $natural

### CODE REVIEW

**Comment by erkie** [comment]
Hi! Saw the ping regarding Corona Dashboard. Would love to discuss more about it (and Ember ofc) we moved to Ember in 2017 and have since migrated over time to Ember + typescript, angle bracket components, and now slowly to octane.

**Comment by amyrlam** [comment]
@erkie thanks for the ping! We can workshop on a GitHub branch off of this PR if you're up for it. Are you on the Ember Discord chat also? I'm @ amyrlam on there or #support-ember-times is our channel

BTW meant to respond to your comment on Discuss sooner! But was a busy week, esp with EmberConf

**Comment by ttill** [comment]
@amyrlam Thanks for bringing my message up, here. Really appreciate this. As we just had a story on another great (QR) code scanner in Ember Times (whose somewhat suboptimal wording triggered my message on discord): Do you think actually actually is any interest in another story on such a niche addon (at least that's what I imagine it to be)?

**Comment by amyrlam** [comment]
@ttill makes sense. how about a correction to the blog post? i can draft a sample PR

aside: maybe we can propose a QR category on https://emberobserver.com/?

**Comment by ttill** [comment]
@amyrlam Yeah sure, although not really a necessity for me personally, that's a good idea.

Regarding adding a catetory on ember observer: Indeed such addons do not fit into any of the existing categories nicely, however a search for "qr code" on ember observer currently only yields 8 results - But then again there are other categories that are even smaller... So I would back such a proposal.

**Comment by amyrlam** [comment]
@ttill sounds good, let me address the old issue soon, and can tag you on the PR. 

also can ping ember observer, let's find out! seems useful. 

thanks for the reply

**Pull request merged**
