### PR TITLE
Covered the story of Ember Madrid at Codemotion 2019

### PR DESCRIPTION
**Pull request by ijlee2**
Based on conference website and direct messaging with Juan on Discord. 
cc:
@shokmaster @adrigzr @svsalvador Feel free to provide us feedback before Friday evening submission (pacific time)
@jessica-jordan Thanks again for helping me learn to add images!

Screen Shot 2019-10-03 at 11 06 34 PM

### CODE REVIEW

**Review by amyrlam — COMMENTED** [review]
👍 looks great

will prob only put one image in the goodbits...but will see what the options are!

**Review by amyrlam — APPROVED** [review]
whoops, meant that to be a :+1:

**Comment by ijlee2** [comment]
Thanks, @amyrlam! Yep, one image on Goodbits sounds good (probably the middle one that shows Ember 3.0?).

I didn't realize the difficulty in translating Markdown to HTML so that we can align images well. Feel free to let me know if you want help with translating HTML back to Markdown for dev.to.

**Comment by amyrlam** [comment]
got the middle one 👍

**Pull request merged**
