### PR TITLE
WIP: The Ember Times Octane Special (No. 130) - January 10, 2020

### PR DESCRIPTION
**Pull request by jayjayjpg**
Let's pick sub topics for this special and coordinate to get the sections together into the post.

### What is Octane?
- [ ] Link to the blog post
- [ ] Description of edition
- [ ] Ask Yehuda or Tom what they’re excited about in regards to Octane. Get quotes / interview into a section

### How to migrate to Octane

- [ ] Highlight the opt-in method for Octane. Migrate in your own time step by step. It might be not clear upfront that people can migrate components incrementally
- [ ]  how to migrate and which tools and guides to use. 
- [ ] Migration Guide available that can be linked to. 
- [ ] Maybe talk to someone who already migrated their app (side project vs work project) and mention that as an interview / quote in the section

### Learning Resources 
- [ ] Link to Guides / API Docs
- [ ] Frontend Masters / Videos / Livestreams
- [ ] Chris Garett’s blog post series

You may ping @jenweber for content reviews or getting connections to potential interviewees

### CODE REVIEW

**Comment by CodingItWrong** [comment]
When y'all decide on the date this issue would be, plz let me know, so I can shoot for that live stream or video recording around then 👍

**Comment by CodingItWrong** [comment]
> How to get started in Octane coming from another framework

I could contribute Vue -> Octane info on this; @NullVoxPopuli proposed this a while back and I never got around to it.

**Comment by NullVoxPopuli** [comment]
Yeah, the atlas has the react thing!. But I'm think we remove the WIP on it, and just accept that things could get out of date :)

**Comment by amyrlam** [comment]
- [ ] the ember atlas (unofficial, but good resource) https://www.notion.so/The-Ember-Atlas-4094f81c86c34badb4a562ed29414ae1

**Comment by NullVoxPopuli** [comment]
emberatlas.com works, too!

And fwiw, it's a good enough resource, that i think it should be the official unofficial guide(s). Linked to from the main site

**Comment by amyrlam** [comment]
octane special: potentially next issue https://github.com/ember-learn/ember-blog/pull/434, or early 2020

**Comment by jayjayjpg** [comment]
I'm closing this one, because I missed to make this a project owned feature branch versus one on my personal repo - feel free to continue discussion over here at the new Octane special PR: https://github.com/ember-learn/ember-blog/pull/459

**Pull request closed without merging**
