### PR TITLE
Normalize post tags

### LINKED ISSUE #816: Clean up tags
As part of #7 we have generated "first class citizen" tags for the blog 🎉  but in doing so we have noticed quite a few tags that need to be cleaned up 😂  There are currently two classifications of cleanup that we are able to do: 

- ignore a tag completely
- unify or normalise tags to remove duplicates

If we feel like we can ignore a tag completely we can just add them to the list used for converting the data: https://github.com/ember-learn/ember-blog/blob/empress-blog/convertData.js#L77 You will notice that we're currently ignoring "Ember Times" and a few variations of that 😱  this is actually ok because **every** tag that has any of these Ember Times variations also has the **newsletter** tag. 

If we can't just ignore a tag then we need to update **master** to fix the tag data so the automatic data conversion script will pick it up correctly 👍 

## Todo: 

- [ ] Normalize a11y and accessible tags to Acessible
- [ ] Normalize Data to Ember Data

### PR DESCRIPTION
**Pull request by locks**
Closes https://github.com/ember-learn/ember-blog/issues/816.

### CODE REVIEW

**Review by mansona — APPROVED** [review]
nice work 🎉

**Comment by mansona** [comment]
I assume this is another one that we want to merge without CI passing @locks ?

**Comment by locks** [comment]
@mansona yeah, pretty sure. I checked CI and it's markdownlint and such.

**Review by ijlee2 — APPROVED** [review]
Thanks for working on updating the tags! I think we can merge this pull request.

**Pull request merged**
