### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by amyrlam**
## What it does

Was thinking about putting the emoji on the LHS so it's kind of a "bullet point". Someone at my work did this and thought it was a good idea! Let me know what you think

### CODE REVIEW

**Comment by chrisrng** [comment]
🆒 Is the idea to replace the emojis with the relevant one for each bullet point?

**Comment by amyrlam** [comment]
@chrisrng yes... i realize that is confusing now. i used a different emoji so that didn't need the changing #'s in each post heading, something quirky about markdownlint not wanting the same title. but could go back to the #'s and keep the emoji constant?

**Comment by ijlee2** [comment]
I prefer that we keep the numbered bullets.

**Comment by amyrlam** [comment]
@chrisrng @ijlee2 thanks for the feedback! what do you think about all tomster hamster emojis and added the #'s back? can def be a "living" document also

**Review by ijlee2 — APPROVED** [review]
I think we can try it out. I don't have a preference. 🙂

**Comment by amyrlam** [comment]
cool let's try it, we can switch back!

**Pull request merged**
