### PR TITLE
Add writeup on 10001

### PR DESCRIPTION
**Pull request by amyrlam**

### CODE REVIEW

**Comment by amyrlam** [comment]
cc @muziejus short writeup for the Ember Times. @'ing just in case you have any feedback (apologies is a bit close to publish time), no worries if not!

**Review by ijlee2 — APPROVED** [review]
Amazing write-up! I appreciate your covering the 10001 story.

**Review by chrisrng — APPROVED** [review]
LGTM! Thanks!

**Comment by muziejus** [comment]
@amyrlam Thanks for the writeup.

**Pull request merged**
