### PR TITLE
Add section about Octane ESLint rules

### PR DESCRIPTION
**Pull request by patocallaghan**
Proposes a section for the latest Ember Times blog post about the new proposed Octane ESLint rules. 

A [number of issues](https://github.com/ember-cli/eslint-plugin-ember/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Help+Wanted%22+Octane+Rule) have been created on the eslint-plugin-ember repo and we'd like to see if anyone is willing to help the initiative. 

If I'm too late for the current blog post, that's all good 👍 Hopefully the copy is okay as I don't do this much 😬

### CODE REVIEW

**Review by rwjblue — COMMENTED** [review]
Looks good to me!

I wonder, @patocallaghan do you think it might make sense to add a similar section (or tweak this one) for the same sort of thing in ember-template-lint ([link of octane issues with help wanted here](https://github.com/ember-template-lint/ember-template-lint/issues?utf8=%E2%9C%93&q=+project%3Aember-template-lint%2F1+label%3A%22help+wanted%22+))?

**Comment by patocallaghan** [comment]
Oh cool, didn't know about those. I'll tweak the copy to include the template lint ones too

**Comment by patocallaghan** [comment]
I've updated the titles and copy to include a mention/link of ember-template-lint

**Review by jayjayjpg — APPROVED** [review]
This reads great! Thank you for this :sparkles: writeup for The Ember Times!

**Pull request merged**
