### PR TITLE
Times 117: Covered the release of Ember 3.13

### PR DESCRIPTION
**Pull request by ijlee2**

### CODE REVIEW

**Comment by ijlee2** [comment]
@kennethlarsen I wrote the summary in a bit of haste (busy day today). Would you mind taking a look and giving me feedback (feel free to suggest things to add and remove)?

Feedback from other reviewers are also welcome as always.

Thanks,

**Comment by amyrlam** [comment]
looks great!

**Review by kennethlarsen — APPROVED** [review]
Looks good to me! Might add a note about 3.12 being promoted to LTS though

**Comment by ijlee2** [comment]
Thanks, @amyrlam and @kennethlarsen . I will add about 3.12 LTS!

**Pull request merged**
