### PR TITLE
Enable most markdownlint defaults

### LINKED ISSUE #213: Markdown linter next steps
Enable rules that we want from https://github.com/ember-learn/ember-blog/pull/211

Add short blurb to README e.g. link to https://github.com/DavidAnson/markdownlint ... and perhaps specifically call out https://github.com/DavidAnson/markdownlint#related

### PR DESCRIPTION
**Pull request by amyrlam**
## What it does

- Enable most markdownlint defaults
  - Reference: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md
- Add markdownlint to CONTRIBUTING

## Related Issue(s)
Closes: https://github.com/ember-learn/ember-blog/issues/213
Follow-on to: https://github.com/ember-learn/ember-blog/pull/211

### CODE REVIEW

**Comment by amyrlam** [comment]
- [x] ~Question: When I run it locally, I get this error message, which is also on Travis?~

~amyrlam@amyrlamComputer ember-blog (amy/markdownlint-rules) 🌒 $ scripts/markdown-lint.sh~
~fatal: remote base already exists.~

~https://travis-ci.org/ember-learn/ember-blog/builds/566826555#L1373-L1375~

~I get the same for alex, but alex seems to work on Travis?~

~amyrlam@amyrlamComputer ember-blog (amy/markdownlint-rules) 🌒 $ bash scripts/language-check.sh~
~fatal: remote base already exists.~

//

@aklkv Wondering if you can take a peek, do you know what am I doing wrong? Everything is working fine for me with the VSCode extension, on new or modified files.

**Comment by aklkv** [comment]
@amyrlam This scripts are design to only work in travis! it will be easier once we move to all js setup with empress. For now I would suggest to us code editor for reference

**Comment by amyrlam** [comment]
@aklkv thanks! that makes sense. 

I am confused why this branch didn't fail due to errors in `source/emberblog-template.md`, but am doing some more testing on the other open branch

**Comment by aklkv** [comment]
@amyrlam I have just submitted a quick fix for your confusion https://github.com/ember-learn/ember-blog/pull/219

**Comment by amyrlam** [comment]
@aklkv super helpful, makes sense now! Didn't even think to check the glob yesterday. 

Will make some adjustments to this branch e.g. we may need `inline-html`

**Comment by amyrlam** [comment]
- [x] This will need a squash and merge (with fixup!) on merge. Please review!

@ember-learn/ember-times-editors You'll want to download the markdownlint extension for your editor https://github.com/DavidAnson/markdownlint#related. There is an extension for alex (language checker that we've been using) as well https://github.com/get-alex/alex#integrations. (Note: A failing build due to linting can always be fixed after the fact as well.) 

We originally implemented the markdownlint to solve some a11y issues! See [this issue](https://github.com/ember-learn/ember-blog/issues/123).

**Comment by amyrlam** [comment]
Let's merge this in and see how it goes this week, can make further edits

**Pull request merged**
