### PR TITLE
Fix middleman-alias

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Review by jenweber — APPROVED** [review]
Seems good. The test failures seem to be because of the linter, and it seems they might be unrelated to these changes. We should confirm.

**Review by amyrlam — APPROVED** [review]
sorry the linters were so noisy! 

i can look into turning them off for old posts entirely if helpful?

**Comment by locks** [comment]
@amyrlam na, I think it's fine. at most we might disable alex for syndicated posts, if we find that it is a problem?

**Comment by amyrlam** [comment]
@locks sure sounds good

**Pull request merged**
