### PR TITLE
Proposal to update Ember Times template

### PR DESCRIPTION
**Pull request by amyrlam**
## What it does

I was thinking the bottom of the email every week is a bit long and we could combine the sections, using the image as a visual separator. What do you think? Open to any and all suggestions!

//

Also, posted on Discord asking if we can get the Readers' Questions to autopost to our channel. Maybe @locks or @jayjayjpg owns this? (I cannot remember)

Part of: https://github.com/ember-learn/ember-blog/issues/577

### CODE REVIEW

**Comment by ijlee2** [comment]
I think we'll want to consider how the current and proposed sections will look in the upcoming blog redesign.

I checked on Docker what the proposed changes mean for the current blog. I noticed a large gap between paragraphs due to the Tomster image. It seemed like we have two sections and require the `` element to appear first, partly to hide CSS not working well.

Screen Shot 2020-06-13 at 7 47 28 AM

I think it'd be good to give the group a week to see this PR and provide you with more feedback. If we decide to combine the two sections into one, I think it'd be good to update the header text into "Connect with us!" (or something else that is general like this).

**Comment by amyrlam** [comment]
I got the form from @jayjayjpg - thank you! 🙇‍♀️ 

//

@ijlee2 Thanks for chiming in! 

Ah sorry about the CSS, hadn't even checked it locally.

I def like `Connect with us` regardless! 

Right now seems like a lot of real estate for every issue at the bottom, when it's not super active. But this is just a proposal for discussion, strongly agree with what you suggested!

**Comment by jayjayjpg** [comment]
I'm also up for shortening the bottom section as a `Connect with us` paragraph that you suggested!

**Comment by amyrlam** [comment]
What do you think? 

IS:
image

**Comment by ijlee2** [comment]
Looks good to me, thanks!

**Comment by abhilashlr** [comment]
Looks good to me as well @amyrlam 🎉

**Review by jayjayjpg — APPROVED** [review]
This looks great, thank you for this :sparkles: update!

**Comment by amyrlam** [comment]
cool let's try it out, consider this a living document, we can change it!

**Pull request merged**
