### PR TITLE
Octane VS Code Plugins

### PR DESCRIPTION
**Pull request by jaredgalanis**
Adds coverage of Octane VS Code Plugins

### CODE REVIEW

**Review by jayjayjpg — APPROVED** [review]
This reads great! Do you mind rebasing this branch onto `blog/embertimes-125` another time? Otherwise this should be good to go and thank you for another :sparkles: writeup this week!

**Comment by amyrlam** [comment]
i'm going to merge in, and fix rebase if still going on upstream

**Comment by pzuraq** [comment]
We discussed this at the core team meeting on Friday, and we actually do not want to recommend the Unstable ELS _or_ the main ELS as part of the default setup for VS Code. Both solutions have their quirks - the Unstable ELS has been moving quickly (which is great!) but has been notably unstable for some users because of this, and the original ELS has not been maintained recently, and was not actually adopted as a project by the core team (e.g. there wasn't an RFC).

Our current plan is to remove the main ELS from the Ember VS Code plugin, and note in its README that it is not Octane ready and currently unmaintained. We should probably revert this PR for the time being.

**Comment by pzuraq** [comment]
@jaredgalanis and I spoke offline, I read a bit too quickly and didn't realize that A. this had gone out and B. we weren't recommending it as an official solution anyways here. The only thing we want to avoid is implying that the ELS/Unstable ELS are the recommended/official plugins, so carry on!

**Comment by amyrlam** [comment]
thanks for resolving this so quickly! @jaredgalanis and pzuraq

@pzuraq - def keep us posted if you want us to write about the official plugin down the road

**Comment by amyrlam** [comment]
FWIW I wrote "🤖 Unofficial Octane @code plugins" on tmrw's tweet

**Pull request merged**
