### PR TITLE
feat(blog): adds 3 ember-modifiers blog post

### PR DESCRIPTION
**Pull request by abhilashlr**

### CODE REVIEW

**Review by amyrlam — COMMENTED** [review]
Thanks for the writeup! 

Looks good, how about we combine it into one story similar to LexasCMS from the other week, with subheadings?

BTW, you should be able to clone the repo directly, if you want to not work on a fork

Added ember-times-editors as reviewer!

**Review by rwjblue — COMMENTED** [review]
Totally up to y'all, but just FYI I've just published ember-modifier@2.0.0. Might be worth mentioning...

Changelog is here https://github.com/ember-modifier/ember-modifier/releases/tag/v2.0.0

**Comment by abhilashlr** [comment]
> Thanks for the writeup!
> 
> Looks good, how about we combine it into one story similar to LexasCMS from the other week, with subheadings?

Thanks @amyrlam. Yeah, I had thought about it. But I also wanted to see if any of the reviewers felt the same way to club them together with subheadings before I make them into 1 group. I will amend the changes. And that's a valuable suggestion 😄 .

> BTW, you should be able to clone the repo directly, if you want to not work on a fork

Sure @amyrlam, will work on it that way from my next PR 👍

**Comment by abhilashlr** [comment]
> Totally up to y'all, but just FYI I've just published ember-modifier@2.0.0. Might be worth mentioning...
> 
> Changelog is here https://github.com/ember-modifier/ember-modifier/releases/tag/v2.0.0

That's a good point @rwjblue 👍 I shall add the changes and get back.

**Comment by ijlee2** [comment]
I think we can group the 3 articles by Raja into one. I got the impression that all 3 (in addition to the one that we had previously covered) were related to one another. However, it has been a while since I read the articles, so I may be wrong in concluding that they formed a series of blog posts.

As for covering `ember-modifier` v2 release, can we make a separate PR so that we can get this one merged soon?

**Review by amyrlam — APPROVED** [review]
Let's merge this in for now. I can make the header updates and add in a note about ember-modifier@2.0.0 upstream. Thanks @abhilashlr for the awesome writeup and @ijlee2 @rwjblue for chiming in, always much appreciated!

**Comment by abhilashlr** [comment]
> Let's merge this in for now. I can make the header updates and add in a note about ember-modifier@2.0.0 upstream. Thanks @abhilashlr for the awesome writeup and @ijlee2 @rwjblue for chiming in, always much appreciated!

Sorry about the delay from my side on this one. Do you want me to still merge them and send a new PR? I can do that @amyrlam

**Comment by abhilashlr** [comment]
Many thanks @amyrlam for reviewing and merging this PR. I've merged the 3 posts into 1 in https://github.com/ember-learn/ember-blog/pull/731. Please review and let me know if there are any changes to be done 👍

**Pull request merged**
