### PR TITLE
The Ember Times No. 140 - March 20th 2020 

### PR DESCRIPTION
**Pull request by amyrlam**
📝 Ideas, feel free to add to list or claim!

- [x] Ember v3.17 released https://blog.emberjs.com/2020/03/16/ember-3-17-released.html (🔒 @ijlee2)
- [ ] RFC: `{{set}}` helper https://github.com/emberjs/rfcs/pull/594
- [x] RFC: Test colocation https://github.com/emberjs/rfcs/pull/599 (reach out to @NullVoxPopuli if questions!) (🔏 @jessica-jordan)
- [x] An update for `rwjblue-style-release-it-setup` by Robert Jackson (rwjblue)
  - https://discordapp.com/channels/480462759797063690/491905849405472769/686891414738829343 (🔏 @jessica-jordan)
- [x] Respect the Underscore (🔒 @ijlee2)
  - https://medium.com/@ritual_steven/respect-the-underscore-331fa23e1595
- [ ] Barcode scanner for Ember apps: https://github.com/evocount/ember-scanner
Thank you very much to the ember-times Team for bringing us exciting news week after week! Just let me throw in that QR (and barcode) scanning without a growth in bundle size (thanks ember-auto-import) has been available for much longer through https://github.com/evocount/ember-scanner ... ping @ ttill on discord for short writeup?
- [ ] We at Feeder also built a COVID-19 aka Corona Dashboard, but for incoming news on the subjects such as news, travel advice and research. It’s also built with Ember.js! It can be found here: https://feeder.co/reader/corona It’s built using our regular stack that ingests public RSS feeds and filters on a set of keywords. https://discuss.emberjs.com/t/ember-js-the-ember-times-issue-no-139/17631/2?u=amyrlam ... ping on discuss for short writeup?
- [x] "Ember Testing Guide" written by Dawid Pośliński (PoslinskiNet) (🔒 @chrisrng )
  - https://twitter.com/poslinskinet/status/1239503392386568192
- [x] CI with GitHub Actions for Ember Apps) (🔒 @ijlee2)
  - https://crunchingnumbers.live/2020/03/17/ci-with-github-actions-for-ember-apps/
- [ ] Release of Tracked Built-Ins v1.0.0
  - https://twitter.com/pzuraq/status/1240069037364633600
- [ ] Refactoring Ember Templates - Quick Tip!
  - https://abhilashlr.in/ember-refactor-templates
- [x] emberconf + story writing request (🔏 @jessica-jordan)
  - [x] https://twitter.com/alex_diliberto/status/1240449629612892161
- [ ] new modifier, if anyone wants to write about it, reach out to @NullVoxPopuli if questions https://twitter.com/nullvoxpopuli/status/1239325059656933376

📆 Future stories
- [ ] **UPDATE** _this should go out in the 2/28 issue per 2/20 learning team meeting_ Write up on current website update status. Call for contributors, explaining the styleguide and which projects contributors can help with. Ping @mansona when this topic is due for release in the Times (Amy note 3/13: is this still valid?)
- [ ] More octane at company x stories? Square, others? (Amy note 3/13: pinged Dean @ Square on Twitter)
- [ ] Outstanding Team Quotes about Octane from https://github.com/ember-learn/ember-blog/pull/459 (Amy note 3/13: is this still valid?)
  * @MelSumner  
  * @kategengler
  * @mixonic
  * @pzuraq

🤔 Questions?

See #support-ember-times on Discord or CONTRIBUTING.

✅ Todos:

- [ ] check all header links are also in the body, and add to template

- Check https://github.com/ember-learn/whats-new-in-emberland (roundup of all the PRs in emberjs and ember-learn repos) for ideas
- Use https://github.com/ember-learn/emberjs-times-tools README
- Check Netlify preview, to ensure display on emberjs.com/blog is good
  - [ ] Check buttons
- [ ] Crosspost on dev.to, delete Readers Question picture, add Canonical URL 
- [ ] Set up tweet for Monday morning on tweetdeck
  - [ ] post $natural

### CODE REVIEW

**Comment by amyrlam** [comment]
Are the future stories still valid? Maybe we can clean house this week / next, as there will probably be a lot of new content with the post-EmberConf rush cc @jessica-jordan

**Comment by jayjayjpg** [comment]
> Are the future stories still valid? Maybe we can clean house this week / next, as there will probably be a lot of new content with the post-EmberConf rush cc @jessica-jordan

Agreed! I think the Octane quotes would still be valuable in case we want to revisit the Octane topic in another special edition some time - if the team is up for it, we could maybe create a branch for that to be published some time in the next weeks / months and put the related future stories there - depending on how big the interest for another special is and how everyone's schedule is like. What are your thoughts in general?

**Comment by amyrlam** [comment]
👍 sounds good to me!

**Comment by NullVoxPopuli** [comment]
new modifier, if anyone wants to write about it 🤷‍♂  https://twitter.com/nullvoxpopuli/status/1239325059656933376

**Comment by amyrlam** [comment]
@NullVoxPopuli will carry over with the list next week, or feel free to submit a blurb to the next PR!

**Comment by NullVoxPopuli** [comment]
Thanks! 
And the write up on the co-location RFC is fantastic! <3

**Pull request merged**
